---
repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v5.9.0
    hooks:
      - id: cspell
        # entry: codespell --relative
        args: ["--relative", "--no-progress", "--no-summary"]
        name: Spell check with cspell
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: "v2.5.1"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            root/Library/Application\ Support/JetBrains/.*
          )$
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: flake8
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck

  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.0
    hooks:
      - id: bashate
        args: ["-i", "E006"]
