dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
ignorePaths:
  - Brewfile
  - root/.config/mc/ini
  - root/.local/share/mc/skins/onedark16M.ini
  - root/.vimrc
  - root/Library/Application Support/Code/User/settings.json
  - root/Library/Application Support/Code/User/spellright.dict
  - root/Library/Application Support/JetBrains/consentOptions/accepted
